#version: '3'
#
#services:
#  mysql:
#    image: mysql:latest
#    container_name: mysql_1
#    restart: unless-stopped
#    ports:
#      - "3306:3306"
#    environment:
#      TZ: Asia/Seoul
#    volumes:
#      - ./mysql/volumes/var/lib/mysql:/var/lib/mysql
#    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
#
#  redis:
#    image: redis:latest
#    container_name: redis_1
#    restart: unless-stopped
#    ports:
#      - "6379:6379"
#    environment:
#      TZ: Asia/Seoul
#
#  nginx:
#    image: nginx:latest
#    container_name: nginx_1
#    restart: unless-stopped
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./nginx/conf.d:/etc/nginx/conf.d
#      - ./nginx/html:/usr/share/nginx/html
#      - ./nginx/log:/var/log/nginx
#      - ./nginx/certs:/etc/nginx/certs
#    environment:
#      TZ: Asia/Seoul
#
#  rabbit-mq:
#    image: rabbitmq:management
#    container_name: rabbitmq-1
#    volumes:
#      - ./dockerProjects/rabbitmq-1/volumes/etc/rabbitmq:/etc/rabbitmq
#      - ./dockerProjects/rabbitmq-1/volumes/var/lib/rabbitmq:/var/lib/rabbitmq
#      - ./dockerProjects/rabbitmq-1/volumes/var/log/rabbitmq:/var/log/rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    environment:
#      RABBITMQ_DEFAULT_USER: admin
#      RABBITMQ_DEFAULT_PASS: admin
#    command: >
#      sh -c "echo 'loopback_users = none' >> /etc/rabbitmq/rabbitmq.conf && rabbitmq-plugins enable rabbitmq_management && rabbitmq-plugins enable rabbitmq_stomp && rabbitmq-plugins enable rabbitmq_mqtt && rabbitmq-server"
