version: '3'

services:
  # Spring Boot 애플리케이션 추가
  hoit-app:
    image: hoit-app:latest
    container_name: hoit-app
    restart: unless-stopped
    ports:
      - "8090:8090"
    environment:
      - TZ=Asia/Seoul
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/midai
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=han1000llm
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_RABBITMQ_HOST=rabbit-mq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=admin
      - SPRING_RABBITMQ_PASSWORD=admin
    depends_on:
      - mysql
      - redis
      - rabbit-mq

  mysql:
    image: mysql:latest
    container_name: mysql_1
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=han1000llm
      - MYSQL_DATABASE=midai
    volumes:
      - ./mysql/volumes/var/lib/mysql:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:latest
    container_name: redis_1
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Seoul

  rabbit-mq:
    image: rabbitmq:management
    container_name: rabbitmq-1
    volumes:
      - ./dockerProjects/rabbitmq-1/volumes/etc/rabbitmq:/etc/rabbitmq
      - ./dockerProjects/rabbitmq-1/volumes/var/lib/rabbitmq:/var/lib/rabbitmq
      - ./dockerProjects/rabbitmq-1/volumes/var/log/rabbitmq:/var/log/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    command: >
      sh -c "echo 'loopback_users = none' >> /etc/rabbitmq/rabbitmq.conf && 
             rabbitmq-plugins enable rabbitmq_management && 
             rabbitmq-plugins enable rabbitmq_stomp && 
             rabbitmq-plugins enable rabbitmq_mqtt && 
             rabbitmq-server"