app:
  client:
    urls: http://localhost:5173,https://hoit.my
server:
  port: 8090
  shutdown: graceful
spring:
  config:
    import: "application-secret.yml"
  autoconfigure:
    exclude:
  lifecycle:
    timeout-per-shutdown-phase: 1h
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/midai
    username: root
    password: 1234
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8090/auth/google/redirect
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        use_sql_comments: false
        dialect: org.hibernate.dialect.MySQLDialect
logging:
  level:
    com.ll.demo03: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.transaction.interceptor: INFO
    org.springframework.security: DEBUG
custom:
  site:
    name: "My Site Prod"