app:
  client:
    url: https://front.hoit.my:3000
server:
  port: 8090
  shutdown: graceful
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  config:
    activate:
      on-profile: default
    import: "application-secret.yml"
  docker:
    compose:
      enabled: false
  autoconfigure:
    exclude:
  lifecycle:
    timeout-per-shutdown-phase: 1h
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.39.248.162:3306/midai
    username: root
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8090/auth/google/redirect
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        use_sql_comments: false
        dialect: org.hibernate.dialect.MySQLDialect
# :small_blue_diamond: Actuator 설정 추가 (서버 설정 바로 아래 or 최하단)
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
logging:
  level:
    com.ll.demo03: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.transaction.interceptor: INFO
    org.springframework.security: DEBUG
    org.springframework.core.env: DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari.HikariDataSource: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.web.client: DEBUG
custom:
  webhook-url: https://api.hoit.my
  site:
    name: "My Site Prod"