server:
  port: 8090
  shutdown: graceful
spring:

  config:
    import: "application-secret.yml"
  autoconfigure:
    exclude:
  lifecycle:
    # 스프링부트가 종료 요청을 받은 후 기다려줄 수 있는 최대한의 시간d
    timeout-per-shutdown-phase: 1h
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.35.137.46:3306/stocknote
    username: root

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8090/auth/google/redirect
  data:
    redis:
      host: 3.35.137.46
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        use_sql_comments: false
        dialect: org.hibernate.dialect.MySQLDialect
logging:
  level:
    com.ll.demo03: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.transaction.interceptor: INFO
custom:
  site:
    name: "My Site Prod"