name: Deploy To EC2 with Full Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: JDK 21버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: gradlew 실행 권한 부여
        run: chmod +x ./gradlew

      - name: application.yml 파일 만들기
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application-secret.yml

      - name: 테스트 및 빌드하기
        run: ./gradlew clean build

      - name: Docker 이미지 빌드
        run: |
          docker build -t hoit-app:latest .
          docker save hoit-app:latest | gzip > hoit-app.tar.gz

      - name: Docker 이미지 및 docker-compose.yml 전송
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: |
            hoit-app.tar.gz
            docker-compose.yml
          target: /home/ubuntu/hoit-server/


      - name: SSH로 EC2에 접속하여 배포
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd /home/ubuntu/hoit-server
            
            echo "🚀 완전한 Docker 배포 시작..."
            
            # Docker 이미지 로드
            echo "📦 새 Docker 이미지 로드 중..."
            docker load < hoit-app.tar.gz
            
            # 기존 hoit-app 컨테이너만 중지 (데이터베이스는 유지)
            echo "🛑 기존 애플리케이션 컨테이너 중지 중..."
            docker-compose stop hoit-app || true
            docker-compose rm -f hoit-app || true
            
            # midai 데이터베이스 확인 (데이터베이스 컨테이너들이 실행 중인 경우)
            if docker-compose ps mysql | grep -q "Up"; then
              echo "🗄️ 데이터베이스 확인 중..."
              docker exec mysql_1 mysql -u root -phan1000llm -e "CREATE DATABASE IF NOT EXISTS midai;" 2>/dev/null || true
            fi
            
            # 모든 서비스 시작 (데이터베이스들 + 새로운 애플리케이션)
            echo "🚀 모든 서비스 시작 중..."
            docker-compose up -d
            
            # 애플리케이션 시작 대기
            echo "⏳ 애플리케이션 시작 대기 중..."
            sleep 60
            
            # 컨테이너 상태 확인
            echo "📊 컨테이너 상태 확인..."
            docker-compose ps
            
            # 애플리케이션 로그 확인
            echo "📋 애플리케이션 로그 (최근 20줄):"
            docker-compose logs --tail=20 hoit-app
            
            # 헬스체크
            echo "🔍 애플리케이션 상태 확인..."
            for i in {1..10}; do
              if curl -f http://localhost:8090/actuator/health >/dev/null 2>&1; then
                echo "✅ 애플리케이션이 정상적으로 시작되었습니다!"
                break
              elif curl -f http://localhost:8090 >/dev/null 2>&1; then
                echo "✅ 애플리케이션이 실행 중입니다!"
                break
              else
                echo "대기 중... ($i/10)"
                sleep 10
              fi
            done
            
            # 최종 상태 요약
            echo ""
            echo "🎯 배포 결과 요약:"
            echo "   - 실행 중인 컨테이너: $(docker-compose ps --services --filter status=running | wc -l)개"
            echo "   - 포트 8090 상태: $(netstat -tlnp | grep ':8090 ' && echo '열림' || echo '닫힘')"
            
            # 모든 컨테이너 상태 출력
            echo ""
            echo "📋 전체 컨테이너 상태:"
            docker-compose ps
            
            # 정리
            rm -f hoit-app.tar.gz
            
            echo "🎉 Docker 배포 완료!"